# Generated by Django 5.1 on 2025-11-12 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('machine_name', models.CharField(max_length=100)),
                ('machine_type', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('installation_date', models.DateField()),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('DOWN', 'Down'), ('DECOMMISSIONED', 'Decommissioned')], default='OPERATIONAL', max_length=20)),
                ('maintenance_frequency_days', models.IntegerField(help_text='Maintenance due every X days')),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, db_index=True, null=True)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('manual_document', models.FileField(blank=True, null=True, upload_to='machine_manuals/')),
                ('machine_photo', models.ImageField(blank=True, null=True, upload_to='machine_photos/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_machines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'machines',
                'ordering': ['machine_id'],
            },
        ),
        migrations.CreateModel(
            name='MachineReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('vibration_level', models.FloatField(blank=True, null=True)),
                ('oil_pressure', models.FloatField(blank=True, null=True)),
                ('runtime_hours', models.IntegerField(blank=True, null=True)),
                ('custom_readings', models.JSONField(blank=True, default=dict)),
                ('inspection_photo', models.ImageField(blank=True, null=True, upload_to='inspection_photos/')),
                ('notes', models.TextField(blank=True)),
                ('is_anomaly', models.BooleanField(db_index=True, default=False)),
                ('anomaly_reason', models.TextField(blank=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='machines.machine')),
            ],
            options={
                'db_table': 'machine_readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['machine_id'], name='machines_machine_086afd_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['next_maintenance_date'], name='machines_next_ma_fc8f01_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['status'], name='machines_status_83686b_idx'),
        ),
        migrations.AddIndex(
            model_name='machinereading',
            index=models.Index(fields=['-timestamp'], name='machine_rea_timesta_dc6584_idx'),
        ),
        migrations.AddIndex(
            model_name='machinereading',
            index=models.Index(fields=['machine', '-timestamp'], name='machine_rea_machine_86c97a_idx'),
        ),
        migrations.AddIndex(
            model_name='machinereading',
            index=models.Index(fields=['is_anomaly'], name='machine_rea_is_anom_8edb38_idx'),
        ),
    ]
